version: "3"
services:
  ws:
    image: ex-jscs-sp-2324:1
    build: .
    environment:
      - NODE_ENV=production
      - DB_URL=mongodb://database
    ports:
      - "7070:9090"
    networks:
      - cinfo-jscs
    depends_on:
      - database
  database:
    image: mongo:5
    ports:
      - "7071:27017"
    volumes:
      - database:/data/db
    networks:
      - cinfo-jscs
volumes:
  database:
networks:
  cinfo-jscs: